# Generated by Django 5.2.4 on 2025-09-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_experience_level_profile_languages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='minimum_project_budget',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='preferred_project_types',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='response_time',
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.TextField(blank=True, help_text='Skills as comma-separated text', null=True),
        ),
    ]
