# Generated by Django 5.2.4 on 2025-09-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_profile_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='profile',
            name='languages',
            field=models.JSONField(blank=True, default=list, help_text='Languages spoken'),
        ),
        migrations.AddField(
            model_name='profile',
            name='minimum_project_budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum budget willing to accept', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_project_types',
            field=models.JSONField(blank=True, default=list, help_text='Preferred types of projects'),
        ),
        migrations.AddField(
            model_name='profile',
            name='response_time',
            field=models.CharField(blank=True, choices=[('within_hour', 'Within an hour'), ('within_few_hours', 'Within a few hours'), ('within_day', 'Within a day'), ('within_few_days', 'Within a few days')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.JSONField(blank=True, default=list, help_text='List of technical skills'),
        ),
    ]
