# Generated by Django 5.2.4 on 2025-09-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_remove_profile_updated_at_profile_languages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='minimum_project_budget',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='preferred_project_types',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='response_time',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skills',
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
