# Generated by Django 5.2.4 on 2025-08-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('development', 'Development'), ('design', 'Design'), ('writing', 'Writing'), ('marketing', 'Marketing'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
