# Generated by Django 5.2.4 on 2025-08-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='experience_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], default='intermediate', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('fixed_price', 'Fixed Price'), ('hourly', 'Hourly')], default='fixed_price', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='project_duration',
            field=models.CharField(choices=[('short_term', 'Short-term (less than 1 month)'), ('medium_term', 'Medium-term (1-3 months)'), ('long_term', 'Long-term (3+ months)')], default='medium_term', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='skills_required',
            field=models.JSONField(blank=True, default=list, help_text='List of required skills'),
        ),
    ]
