# Generated by Django 5.2.4 on 2025-08-27 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_experience_level_job_job_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('fixed_price', 'Fixed Price'), ('hourly', 'Hourly Rate')], default='fixed_price', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='project_duration',
            field=models.CharField(choices=[('short_term', 'Short Term (1-30 days)'), ('medium_term', 'Medium Term (1-3 months)'), ('long_term', 'Long Term (3+ months)')], default='medium_term', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='skills_required',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
